[general]
library_name = "lib_BinaryPlayground"
output_file_path = "./BinaryPlayground_library.jl"
module_name = "LibBinaryPlayground"
#jll_pkg_name = "BinaryPlayground_jll"
prologue_file_path = "prologue.jl"
